POST   http://localhost:3030/login?ip="dwd"
content-type: application/json

{
    "id": "user2",
    "password": "user2"
}

###
POST    http://localhost:3030/signup?ip="dwd"
content-type: application/json

{
    "id": "user2",
    "password": "user2"
}

###
POST     http://localhost:3030/logout

###
POST     http://localhost:3030/offers?ip="dwd"
content-type: application/json

{
    "Add": {
        "security": "BTC",
        "side": "Buy",
        "amount": 100,
        "price": 10
    }
}

###
POST     http://localhost:3030/offers?ip="dwdd"
content-type: application/json

{
    "Delete": 767
}