POST   http://localhost:3030/login
content-type: application/json

{
    "id": "user2",
    "password": "user2"
}

###
POST    http://localhost:3030/signup
content-type: application/json

{
    "id": "user2",
    "password": "user2"
}

###
POST     http://localhost:3030/logout
